### ISSUE TITLE
False positive with hashing

### ISSUE THREAD

**Issue by nickbabcock** [dtolnay/no-panic#54]
no-panic is causing a panic with:

```bash
cargo run --release < Cargo.toml
```

In a simple project that wraps the highway hash crate:

Cargo.toml:

```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"

[dependencies]
no-panic = "0.1"
highway = "1.1"

[profile.release]
lto = "thin" # we call to non-generic non-inline
             # functions from a different crate
```

main.rs:

```rust
use std::io::Read;
use highway::{PortableHash, HighwayHash};
use no_panic::no_panic;

#[no_panic]
fn hash_data(mut hasher: PortableHash, data: &[u8]) -> u64 {
    hasher.append(data);
    1 // hasher.finalize64()
}

fn main() {
    let stdin = std::io::stdin();
    let mut data = Vec::new();
    stdin.lock().read_to_end(&mut data).unwrap();
    let hasher = PortableHash::default();
    println!("{}", hash_data(hasher, &data));
}
```

Why do I think this doesn't panic?

- Tracing through `cargo asm` output, I did not see any code related to panics emitted (eg: no `slice_end_index_len_fail` / unwraps, etc):
  ```bash
  git clone https://github.com/nickbabcock/highway-rs.git
  cd highway-rs
  cargo asm --lib highway::portable::PortableHash::append
  cargo asm --lib highway::portable::PortableHash::update 0
  ```
- There are are some references to memcpy, but afaik those don't panic and simplifying the underlying code to remove memcpy is still causing the false positive.
- The rust compiler determined that the [highwayhash wasm payload](https://github.com/nickbabcock/highwayhasher/pull/49) can omit a memory allocator, which afaik the stack unwinding panic handler would otherwise require.
- Followed instructions to run on release, use linker with thin LTO, and not use panic abort.

[I know your viewpoint that there can't be false positives](https://github.com/dtolnay/no-panic/issues/41#issuecomment-1454435782), so I'm scratching my head a bit about where the panic is thought to be coming from and why I think there is a discrepancy.
